### ISSUE TITLE
ETB behavior on 4chan 

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#100] opened 2023-02-13 05:21 UTC
So I have had differing experiences with Hellen-based hardware on hellen154 vs 4chan

On Hyundai 154, I can use autotune just fine, and the PID settings are usually 
P = 0xx.xx
I = 0xxx.xx
D = 0.xxxx

On 4chan
P = 0x.xx (usually around 0.8-2)
I = 0xx.xx (usually around 10-15)
D = 0.0xxx (usually around 0.02-0.09)
Using autotune drives it too crazy, and usually overheats. Using settings by hand usually makes it works quite well.

**Comment by rusefillc** [comment] 2023-02-13 05:40
@Qwerty-OFF any ideas why would Hellen-based Hyundai 154 use ETB PID settings matching Proteus while Hellen-based would be pretty different, with PID auto-tune working on Proteus and Hyundai 154 but failing on 4chan?

**Comment by mck1117** [comment] 2023-02-13 09:40
What sort of capacitors does hyundai board use near the ETB chip? Ceramic or electrolytic?

Proteus -> electrolytic

4chan -> ceramic

**Comment by rusefillc** [comment] 2023-02-13 14:31
old hyundai https://raw.githubusercontent.com/wiki/rusefi/rusefi/Hardware/Hellen/hellen154hyundai-rev-b.jpg ceramic?

new hyundai I do not have any photo :( @ElDominio ?

8chan ceramic

**Comment by Qwerty-OFF** [comment] 2023-02-27 22:38
![image](https://user-images.githubusercontent.com/4116383/221701843-dde361bc-0293-48e8-ba95-4923599bac79.png)

**Comment by rusefillc** [comment] 2023-02-28 02:00
@mck1117 adding electrolytic did not change anything :(

![image](https://user-images.githubusercontent.com/48498823/221733504-ac6db9a1-0847-40cf-a1a3-3d36d251bbf5.png)

**Comment by rusefillc** [comment] 2023-03-16 20:07
@dron0gus says

![image](https://user-images.githubusercontent.com/48498823/225740634-19830081-dafa-4770-9191-12b076f739bd.png)

![image](https://user-images.githubusercontent.com/48498823/225740678-9f470ab9-f27f-4771-8762-4d5db9c9eded.png)

**Comment by rusefillc** [comment] 2023-03-16 20:32
that did not help :(

![WhatsApp Image 2023-03-16 at 16 21 34](https://user-images.githubusercontent.com/48498823/225745829-507f21e9-b14e-4264-b445-9f61c3c762da.jpg)


![WhatsApp Image 2023-03-16 at 16 30 23](https://user-images.githubusercontent.com/48498823/225745865-5ce3a32c-efdc-418b-be02-6aa9987e8f3e.jpg)

**Comment by rusefillc** [comment] 2023-03-16 20:34
@mck1117 @andreika-git I am out of ideas. Sounds like we need an EE person to touch this? Would any sort of logs help do we even log useful stuff?

#109 created because why not

**Comment by rusefillc** [comment] 2023-03-16 20:52
https://github.com/rusefi/alphax-4chan/issues/110 another crazy one

**Comment by mck1117** [comment] 2023-03-16 20:58
I don't think there are any useful logs to have here that aren't an oscilloscope.

**Comment by mck1117** [comment] 2023-03-16 21:01
actually, can you take a maxed out TS rate log of auto calibrate both in the GOOD and BAD scenarios, for clear side-by-side comparison?

**Comment by rusefillc** [comment] 2023-03-21 22:10
@mck1117 poke about above good vs bad

**Comment by andreika-git** [comment] 2023-03-24 20:48
The 4chan log has "OBD_TPS1_Correlation" error, which means the problem is with TPS1 (hardware or wrong settings?) - that's why PID autotune fails.

**Comment by mck1117** [comment] 2023-03-24 21:16
bad left, good right

![image](https://user-images.githubusercontent.com/568254/227642826-8adc88c0-8e8c-4af9-9f62-849075613967.png)

In the good case, it looks more sinusoidal, and in the bad case, it looks much steeper on opening than closing.

In the bad case there are also some weird "runt" cycles like this:
![image](https://user-images.githubusercontent.com/568254/227643157-1c7ea41b-cfdc-4ee8-b642-4ac585c9d645.png)

In the good case it's much more "stable"

**Comment by mck1117** [comment] 2023-03-24 21:21
> The 4chan log has "OBD_TPS1_Correlation" error, which means the problem is with TPS1 (hardware or wrong settings?) - that's why PID autotune fails.
> 
> The OBD_TPS1_Correlation error appears when one of TPS sensors (TPS1 or TPS2) has an invalid signal. As a test, we can disable the TPS2 and try in 'ignoreSecond' mode.

That warning isn't active at the time autotune is running. That's not the problem.

**Comment by mck1117** [comment] 2023-03-24 21:23
> that's why PID autotune fails.

The logs show the firmware is doing fine, and doing the same thing in both cases. It also looks like something is electrically or mechanically wrong: see the weird TPS waveform on the "bad" log.

**Comment by mck1117** [comment] 2023-03-24 21:30
Wait, alphax 4chan is using pin C6 for PWM.

`stm32_common.cpp` says

![image](https://user-images.githubusercontent.com/568254/227644634-1562fe68-82c9-4602-a4a9-6af387d1504a.png)

But `mcuconf_common_f4_f7.h` says

![image](https://user-images.githubusercontent.com/568254/227644695-cc4580f0-d4a7-4287-89c7-afa29f68c671.png)

4CHAN IS USING SOFTWARE PWM FOR ETB

**Closed** 2023-03-27 13:25 UTC
Labels: rev-G

**Comment by mck1117** [comment] 2023-03-27 17:40
> Damn that's a shameful issue :(

this should be a lesson for “electrical weirdness -> get out a scope and look at it instead of shooting in the dark for a month”

**Comment by ElDominio** [comment] 2023-03-29 16:16
@rusefillc was this tested before closing?

**Comment by rusefillc** [comment] 2023-03-29 16:32
> @rusefillc was this tested before closing?

yes. my bad not posting happy artifacts

and this justifies a new release actually!

**Comment by ElDominio** [comment] 2023-03-29 21:27
Tested today, way, way better results! :D
