### ISSUE TITLE
ibom: cannot click on passives above D203

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#131] opened 2023-05-04 23:29 UTC
https://rusefi.com/docs/ibom/alphax_4ch-g-ibom.html

Good:
![image](https://github.com/rusefi/alphax-4chan/assets/48498823/64b2f26c-3082-448f-952c-2dc9b2d4844b)

Bad:
cannot do this with similar components right above D203

**Comment by andreika-git** [comment] 2023-05-10 17:52
Cannot reproduce (works on both Chrome and Firefox):

![image](https://github.com/rusefi/alphax-4chan/assets/15104768/98807ae3-3cc6-4a7b-8f0f-be24e16396ed)

**Comment by rusefillc** [comment] 2023-05-10 17:58
step 1: click https://rusefi.com/docs/ibom/alphax_4ch-g-ibom.html
step 2: do NOT click "FB" mode
step 3: click above D204 happy
step 3: click above D203 unhappy

**Comment by andreika-git** [comment] 2023-05-10 20:04
Some of 10k/0402 resistors have wrong part numbers (510k instead of 10k). That's why they were duplicated in the BOM - and it could possibly cause this bug of partial selection (those resistors above D203 are 10k). Maybe we should fix the mega-mcu BOM first and then continue to test the 4chan iBom.

**Comment by rusefillc** [comment] 2023-05-10 21:14
@andreika-git стоит ли нам защищаться от некорректных данных, или непросто?

**Comment by andreika-git** [comment] 2023-05-11 12:54
> @andreika-git стоит ли нам защищаться от некорректных данных, или непросто?

https://github.com/andreika-git/hellen-one/issues/293

**Comment by rusefillc** [comment] 2023-05-15 13:30
@Qwerty-OFF please mention relevant 4chan changes just to have a changelog

**Comment by Qwerty-OFF** [comment] 2023-05-15 20:13
Вот у этих компонентов была неправильный PN. Вместо 10k стали 510k.
"10k","R102, R108, R109, R121, R127, R128, R141, R142, R232, R233, R234","R0402","C11616"
В ревизии h все кроме R232 получили правильный PN "C25744". R232 стал DNP (была ошибка в rev. g - https://github.com/rusefi/alphax-4chan/issues/137)

**Comment by rusefillc** [comment] 2023-05-16 16:41
@Qwerty-OFF @andreika-git this ticket is about ibom glitch.

If we have something important going on with five rev G boards in the wild please improve the messaging and making it more obvious what is the level of risk where etc.

**Comment by andreika-git** [comment] 2023-05-16 18:46
https://github.com/andreika-git/hellen-one/issues/295

**Comment by andreika-git** [comment] 2023-05-18 20:02
Fixed by fixing https://github.com/andreika-git/hellen-one/issues/295

**Closed by andreika-git** 2023-05-18 20:02 UTC
Labels: rev-H
